
# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
np.zeros(10)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



### Create a numpy array with values ranging from 10 to 49

In [3]:
# your code goes here
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
# your code goes here
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
# your code goes here
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [18]:
# your code goes here
np.full_like(X,1)

array([[1, 1],
       [1, 1],
       [1, 1]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
# your code goes here
np.full_like(X,0)



### Create a numpy matrix of 4*4 integers, filled with fives.

In [20]:
# your code goes here
np.ones((4,4), dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
# your code goes here
np.full_like(X,7)



### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [21]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [23]:
# your code goes here
np.random.randint(1,10,dtype=int,size=3)

array([6, 6, 3])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [28]:
# your code goes here
np.random.rand(3,3,3)

array([[[0.540563  , 0.83897719, 0.22038394],
        [0.59708715, 0.27927883, 0.24835052],
        [0.58081219, 0.99951786, 0.62399797]],

       [[0.83781651, 0.96428558, 0.24339535],
        [0.12021665, 0.26491314, 0.54658034],
        [0.11979762, 0.36200884, 0.95159557]],

       [[0.63524478, 0.14186513, 0.33415608],
        [0.55455889, 0.63533108, 0.36609887],
        [0.3790767 , 0.59544237, 0.65688731]]])



### Given the X python list convert it to an Y numpy array

In [ ]:
# your code goes here
np.asarray(X)



### Given the X numpy array, make a copy and store it on Y.

In [ ]:
# your code goes here
Y = np.copy(X)



### Create a numpy array with numbers from 1 to 10

In [29]:
# your code goes here
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])



### Create a numpy array with the odd numbers between 1 to 10

In [30]:
# your code goes here
np.arange(1,10,2)

array([1, 3, 5, 7, 9])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [32]:
# your code goes here
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here
Z.size*Z.itemsize

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [ ]:
# your code goes here
X[0]



### Given the X numpy array, show it's last element

In [ ]:
# your code goes here
X[-1]



### Given the X numpy array, show it's first three elements

In [35]:
# your code goes here
X[0:3]

array([1, 2, 3])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [37]:
# your code goes here
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Given the X numpy array, show all middle elements

In [44]:
# your code goes here
start, end = int(len(X)/4), int(len(X)*3/4)+1
X[start:end]

array([3, 4, 5, 6, 7])



### Given the X numpy array, show the elements in reverse position

In [ ]:
# your code goes here




### Given the X numpy array, show the elements in an odd position

In [45]:
# your code goes here
X[1::2]

array([2, 4, 6, 8])



### Given the X numpy matrix, show the first row elements

In [48]:
# your code goes here
X[0,:]

array([0, 1, 2])



### Given the X numpy matrix, show the last row elements

In [50]:
# your code goes here
X[-1,:]

array([6, 7, 8])



### Given the X numpy matrix, show the first element on first row

In [51]:
# your code goes here
X[0,0]

0



### Given the X numpy matrix, show the last element on last row

In [52]:
# your code goes here
X[-1,-1]

8



### Given the X numpy matrix, show the middle row elements

In [55]:
# your code goes here
middle = int(len(X)/2) + 1
X[middle,:]

array([6, 7, 8])



### Given the X numpy matrix, show the first two elements on the first two rows

In [56]:
# your code goes here
X[0:2,0:2]

array([[0, 1],
       [3, 4]])



### Given the X numpy matrix, show the last two elements on the last two rows

In [61]:
# your code goes here
X[-2:,-2:]

array([[4, 5],
       [7, 8]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [63]:
# your code goes here
X.astype(float)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])



### Reverse the given numpy array (first element becomes last)

In [64]:
# your code goes here
X[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])



### Order (sort) the given numpy array

In [65]:
# your code goes here
np.sort(X)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Given the X numpy array, set the fifth element equal to 1

In [68]:
# your code goes here
X[4]=1
X

array([45, 46, 47, 48,  1, 50, 51, 52, 53, 54])



### Given the X numpy array, change the 50 with a 40

In [69]:
# your code goes here
np.where(X==50,40,X)

array([45, 46, 47, 48,  1, 40, 51, 52, 53, 54])


### Given the X numpy matrix, change the last row with all 1

In [71]:
# your code goes here
X[-1,:]=1
X

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])


### Given the X numpy matrix, change the last item on the last row with a 0

In [72]:
# your code goes here
X[-1,-1]=0
X

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 0]])


### Given the X numpy matrix, add 5 to every element

In [73]:
# your code goes here
X+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 6,  6,  5]])


## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [74]:
# your code goes here
X<0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])


### Given the X numpy array, get the negative elements

In [75]:
# your code goes here
X[X<0]

array([-6])


### Given the X numpy array, get numbers higher than 5

In [81]:
# your code goes here
X[X>5]

array([ 6,  7,  8,  9, 10,  6,  6])


### Given the X numpy array, get numbers higher than the elements mean

In [83]:
# your code goes here
X[X>X.mean()]

array([ 7,  8,  9, 10])


### Given the X numpy array, get numbers equal to 2 or 10

In [85]:
# your code goes here
X[(X==2) | (X==10)]

array([10])


## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [86]:
# your code goes here
X.all()

True


### Given the X numpy array, return True if any of its elements is zero

In [87]:
# your code goes here
~X.all()

False


## Summary statistics

### Given the X numpy array, show the sum of its elements

In [88]:
# your code goes here
sum(X)

array([19, 21, 16])


### Given the X numpy array, show the mean value of its elements

In [90]:
# your code goes here
X.mean()

6.222222222222222


### Given the X numpy matrix, show the sum of its columns

In [91]:
# your code goes here
sum(X)

array([19, 21, 16])


### Given the X numpy matrix, show the mean value of its rows

In [93]:
# your code goes here
X.mean(1)

array([6.        , 9.        , 3.66666667])

### Given the X numpy array, show the max value of its elements

In [95]:
# your code goes here
X.max()

10